package com.advintic.integrator.module.irc;
// Generated Dec 17, 2019 10:15:40 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;

/**
 * Worklist generated by hbm2java
 */
@Entity
@Table(name="Integration")
public class Claim implements java.io.Serializable {


    @Id
    private Long rowLine;
    private String invoice_Number;
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private java.sql.Timestamp invoice_Date;
    private String ins_CardNo;
    private String insurance_Co;
    private String associated_Co;
    private String plan_Network;
    private String patient_Id;
    private Long visit_Id;
    private String patient_Name;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private java.sql.Timestamp pat_Dob;
    private String gender;
    private String emirated_Id;
    private String doc_Name;
    private String doc_LicenseNo;

    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private java.sql.Timestamp test_Date;
    private String test_Name;
    private String test_Code;
    private String cpt_Code;
    private String cpt_Type;
    private Long test_Qty;
    private Double amount;
    private Double totalAmount;
    private Double discount_Amt;
    private Double copay_PatientShare;
    private Double net_Amt;
    private Double bp_Systolic;
    private Double bp_Diastolic;
    private String toothNumber;
    private String diagnosis_Code;
    private String branchName;
    private String branchLicenseNo;
    private String priorAuthorizationId;
    private String department_Name;


    public Long getRowLine() {
        return rowLine;
    }

    public void setRowLine(Long rowLine) {
        this.rowLine = rowLine;
    }


    public String getInvoice_Number() {
        return invoice_Number;
    }

    public void setInvoice_Number(String invoiceNumber) {
        this.invoice_Number = invoiceNumber;
    }


    public java.sql.Timestamp getInvoice_Date() {
        return invoice_Date;
    }

    public void setInvoice_Date(java.sql.Timestamp invoiceDate) {
        this.invoice_Date = invoiceDate;
    }


    public String getIns_CardNo() {
        return ins_CardNo;
    }

    public void setIns_CardNo(String insCardNo) {
        this.ins_CardNo = insCardNo;
    }


    public String getInsurance_Co() {
        return insurance_Co;
    }

    public void setInsurance_Co(String insuranceCo) {
        this.insurance_Co = insuranceCo;
    }


    public String getAssociated_Co() {
        return associated_Co;
    }

    public void setAssociated_Co(String associatedCo) {
        this.associated_Co = associatedCo;
    }


    public String getPlan_Network() {
        return plan_Network;
    }

    public void setPlan_Network(String planNetwork) {
        this.plan_Network = planNetwork;
    }


    public String getPatient_Id() {
        return patient_Id;
    }

    public void setPatient_Id(String patientId) {
        this.patient_Id = patientId;
    }


    public Long getVisit_Id() {
        return visit_Id;
    }

    public void setVisit_Id(Long visitId) {
        this.visit_Id = visitId;
    }


    public String getPatient_Name() {
        return patient_Name;
    }

    public void setPatient_Name(String patientName) {
        this.patient_Name = patientName;
    }


    public java.sql.Timestamp getPat_Dob() {
        return pat_Dob;
    }

    public void setPat_Dob(java.sql.Timestamp patDob) {
        this.pat_Dob = patDob;
    }


    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }


    public String getEmirated_Id() {
        return emirated_Id;
    }

    public void setEmirated_Id(String emiratedId) {
        this.emirated_Id = emiratedId;
    }


    public String getDoc_Name() {
        return doc_Name;
    }

    public void setDoc_Name(String docName) {
        this.doc_Name = docName;
    }


    public String getDoc_LicenseNo() {
        return doc_LicenseNo;
    }

    public void setDoc_LicenseNo(String docLicenseNo) {
        this.doc_LicenseNo = docLicenseNo;
    }


    public java.sql.Timestamp getTest_Date() {
        return test_Date;
    }

    public void setTest_Date(java.sql.Timestamp testDate) {
        this.test_Date = testDate;
    }


    public String getTest_Name() {
        return test_Name;
    }

    public void setTest_Name(String testName) {
        this.test_Name = testName;
    }


    public String getTest_Code() {
        return test_Code;
    }

    public void setTest_Code(String testCode) {
        this.test_Code = testCode;
    }


    public String getCpt_Code() {
        return cpt_Code;
    }

    public void setCpt_Code(String cptCode) {
        this.cpt_Code = cptCode;
    }


    public String getCpt_Type() {
        return cpt_Type;
    }

    public void setCpt_Type(String cptType) {
        this.cpt_Type = cptType;
    }


    public Long getTest_Qty() {
        return test_Qty;
    }

    public void setTest_Qty(Long testQty) {
        this.test_Qty = testQty;
    }


    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }


    public Double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }


    public Double getDiscount_Amt() {
        return discount_Amt;
    }

    public void setDiscount_Amt(Double discountAmt) {
        this.discount_Amt = discountAmt;
    }


    public Double getCopay_PatientShare() {
        return copay_PatientShare;
    }

    public void setCopay_PatientShare(Double copayPatientShare) {
        this.copay_PatientShare = copayPatientShare;
    }


    public Double getNet_Amt() {
        return net_Amt;
    }

    public void setNet_Amt(Double netAmt) {
        this.net_Amt = netAmt;
    }


    public Double getBp_Systolic() {
        return bp_Systolic;
    }

    public void setBp_Systolic(Double bpSystolic) {
        this.bp_Systolic = bpSystolic;
    }


    public Double getBp_Diastolic() {
        return bp_Diastolic;
    }

    public void setBp_Diastolic(Double bpDiastolic) {
        this.bp_Diastolic = bpDiastolic;
    }


    public String getToothNumber() {
        return toothNumber;
    }

    public void setToothNumber(String toothNumber) {
        this.toothNumber = toothNumber;
    }


    public String getDiagnosis_Code() {
        return diagnosis_Code;
    }

    public void setDiagnosis_Code(String diagnosisCode) {
        this.diagnosis_Code = diagnosisCode;
    }


    public String getBranchName() {
        return branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }


    public String getBranchLicenseNo() {
        return branchLicenseNo;
    }

    public void setBranchLicenseNo(String branchLicenseNo) {
        this.branchLicenseNo = branchLicenseNo;
    }


    public String getPriorAuthorizationId() {
        return priorAuthorizationId;
    }

    public void setPriorAuthorizationId(String priorAuthorizationId) {
        this.priorAuthorizationId = priorAuthorizationId;
    }


    public String getDepartment_Name() {
        return department_Name;
    }

    public void setDepartment_Name(String departmentName) {
        this.department_Name = departmentName;
    }
}


