package com.advintic.integrator.db.model;
// Generated Dec 17, 2019 10:15:40 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Worklist generated by hbm2java
 */
@Entity
@Table(name="worklist"
    , uniqueConstraints = @UniqueConstraint(columnNames="accession_number") 
)
public class Worklist  implements java.io.Serializable {


     private Integer id;
     private Date creationDateTime;
     private String patientId;
     private Date patientBirthdate;
     private String patientFullName;
     private String patientNationalId;
     private String patientSex;
     private String accessionNumber;
     private String examName;
     private String modalityName;
     private String worklistStatus;
     private int handled;
     private String examCompleted;
    private String comments;
    private String physician;
    private String contrastAllergy;
    private Integer patientPregnant;

    public Worklist() {
    }

	
    public Worklist(Date creationDateTime, String patientId, Date patientBirthdate, String patientFullName, String accessionNumber, String worklistStatus, int handled) {
        this.creationDateTime = creationDateTime;
        this.patientId = patientId;
        this.patientBirthdate = patientBirthdate;
        this.patientFullName = patientFullName;
        this.accessionNumber = accessionNumber;
        this.worklistStatus = worklistStatus;
        this.handled = handled;
    }
    public Worklist(Date creationDateTime, String patientId, Date patientBirthdate, String patientFullName, String patientNationalId, String patientSex, String accessionNumber, String examName, String modalityName, String worklistStatus, int handled, String examCompleted) {
       this.creationDateTime = creationDateTime;
       this.patientId = patientId;
       this.patientBirthdate = patientBirthdate;
       this.patientFullName = patientFullName;
       this.patientNationalId = patientNationalId;
       this.patientSex = patientSex;
       this.accessionNumber = accessionNumber;
       this.examName = examName;
       this.modalityName = modalityName;
       this.worklistStatus = worklistStatus;
       this.handled = handled;
       this.examCompleted = examCompleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date_time", nullable=false)
    public Date getCreationDateTime() {
        return this.creationDateTime;
    }
    
    public void setCreationDateTime(Date creationDateTime) {
        this.creationDateTime = creationDateTime;
    }

    
    @Column(name="patient_id", nullable=false, length=50)
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="patient_birthdate", nullable=false, length=10)
    public Date getPatientBirthdate() {
        return this.patientBirthdate;
    }
    
    public void setPatientBirthdate(Date patientBirthdate) {
        this.patientBirthdate = patientBirthdate;
    }

    
    @Column(name="patient_full_name", nullable=false, length=200)
    public String getPatientFullName() {
        return this.patientFullName;
    }
    
    public void setPatientFullName(String patientFullName) {
        this.patientFullName = patientFullName;
    }

    
    @Column(name="patient_national_id", length=100)
    public String getPatientNationalId() {
        return this.patientNationalId;
    }
    
    public void setPatientNationalId(String patientNationalId) {
        this.patientNationalId = patientNationalId;
    }

    
    @Column(name="patient_sex", length=1)
    public String getPatientSex() {
        return this.patientSex;
    }
    
    public void setPatientSex(String patientSex) {
        this.patientSex = patientSex;
    }

    
    @Column(name="accession_number", unique=true, nullable=false, length=100)
    public String getAccessionNumber() {
        return this.accessionNumber;
    }
    
    public void setAccessionNumber(String accessionNumber) {
        this.accessionNumber = accessionNumber;
    }

    
    @Column(name="exam_name", length=200)
    public String getExamName() {
        return this.examName;
    }
    
    public void setExamName(String examName) {
        this.examName = examName;
    }

    
    @Column(name="modality_name", length=10)
    public String getModalityName() {
        return this.modalityName;
    }
    
    public void setModalityName(String modalityName) {
        this.modalityName = modalityName;
    }

    
    @Column(name="worklist_status", nullable=false, length=1)
    public String getWorklistStatus() {
        return this.worklistStatus;
    }
    
    public void setWorklistStatus(String worklistStatus) {
        this.worklistStatus = worklistStatus;
    }

    
    @Column(name="handled", nullable=false)
    public int getHandled() {
        return this.handled;
    }
    
    public void setHandled(int handled) {
        this.handled = handled;
    }

    
    @Column(name="exam_completed", length=1)
    public String getExamCompleted() {
        return this.examCompleted;
    }
    
    public void setExamCompleted(String examCompleted) {
        this.examCompleted = examCompleted;
    }

    @Column(name="comments")
    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name="physician")
    public String getPhysician() {
        return physician;
    }

    public void setPhysician(String physician) {
        this.physician = physician;
    }

    @Column(name="contrast_allergy")
    public String getContrastAllergy() {
        return contrastAllergy;
    }

    public void setContrastAllergy(String contrastAllergy) {
        this.contrastAllergy = contrastAllergy;
    }

    @Column(name="patient_pregnant")
    public Integer getPatientPregnant() {
        return patientPregnant;
    }

    public void setPatientPregnant(Integer patientPregnant) {
        this.patientPregnant = patientPregnant;
    }
}


